#!/usr/bin/env python3
"""Build Flax's native tools and use its local Rust sources from a consumer."""

import argparse
import json
import os
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]


def run(command, **kwargs):
    subprocess.run([str(part) for part in command], check=True, **kwargs)


def cargo_config(build):
    packages = json.loads((ROOT / 'integration/rust-packages.json').read_text())
    registry = json.loads((ROOT / 'third_party/rust-registry.json').read_text())
    # Cargo expects a flat directory source; physical sources stay in their
    # functional categories. This disposable view contains only relative links.
    view = build / 'cargo-registry'
    view.mkdir(parents=True, exist_ok=True)
    wanted = set()
    for package in registry['packages']:
        name = package['name'] + '-' + package['version']
        wanted.add(name)
        source = ROOT / package['path']
        if not (source / '.cargo-checksum.json').is_file():
            raise ValueError(f'Missing vendored package: {source}')
        link = view / name
        relative = os.path.relpath(source, view)
        if link.is_symlink():
            if os.readlink(link) != relative:
                link.unlink()
                link.symlink_to(relative, target_is_directory=True)
        elif link.exists():
            raise ValueError(f'Refusing to replace a non-symlink: {link}')
        else:
            link.symlink_to(relative, target_is_directory=True)
    for link in view.iterdir():
        if link.name not in wanted:
            if not link.is_symlink():
                raise ValueError(f'Unexpected non-symlink in generated registry: {link}')
            link.unlink()

    protoc = build / 'install/bin/protoc'
    if not protoc.is_file():
        raise ValueError('Build protoc first: python3 scripts/flax.py build-native')
    quote = json.dumps
    lines = ['# Generated by scripts/flax.py; do not commit.', '[patch.crates-io]']
    for name, path in packages.items():
        lines.append(f'{quote(name)} = {{ path = {quote(str(ROOT / path))} }}')
    lines += [
        '', '[source.crates-io]', 'replace-with = "flax-vendored"',
        '', '[source.flax-vendored]', f'directory = {quote(str(view))}',
        '', '[net]', 'offline = true',
        '', '[resolver]', 'incompatible-rust-versions = "fallback"',
        '', '[env]',
        f'PROTOC = {{ value = {quote(str(protoc))}, force = true }}',
        f'PROTOC_INCLUDE = {{ value = {quote(str(build / "install/include"))}, force = true }}',
    ]
    config = build / 'cargo-config.toml'
    config.write_text('\n'.join(lines) + '\n')
    return config


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--build-dir', type=Path, default=ROOT / 'build')
    sub = parser.add_subparsers(dest='command', required=True)
    native = sub.add_parser('build-native', help='Build and install local Protobuf and protoc')
    native.add_argument('--jobs', type=int, default=2)
    cargo = sub.add_parser('cargo', help='Run Cargo with Flax patches and offline sources')
    cargo.add_argument('arguments', nargs=argparse.REMAINDER)
    args = parser.parse_args()
    build = args.build_dir.resolve()
    build.mkdir(parents=True, exist_ok=True)
    if args.command == 'build-native':
        if args.jobs < 1:
            parser.error('--jobs must be positive')
        run(['cmake', '-S', ROOT, '-B', build / 'native',
             '-DCMAKE_BUILD_TYPE=Release', f'-DCMAKE_INSTALL_PREFIX={build / "install"}',
             '-DCMAKE_INSTALL_LIBDIR=lib'])
        run(['cmake', '--build', build / 'native', '--parallel', args.jobs])
        run(['cmake', '--install', build / 'native'])
        run([build / 'install/bin/protoc', '--version'])
    else:
        config = cargo_config(build)
        env = os.environ.copy()
        # Keep caches and build products outside vendored sources and user settings.
        env['CARGO_HOME'] = str(build / 'cargo-home')
        env['CARGO_TARGET_DIR'] = str(build / 'rust-target')
        run(['cargo', '--config', config, *args.arguments], env=env)


if __name__ == '__main__':
    try:
        main()
    except (ValueError, OSError) as error:
        sys.exit(str(error))
    except subprocess.CalledProcessError as error:
        sys.exit(error.returncode)
